Treinamento/force-app/main/default/objects/Carro__c/Carro__c.object-meta.xml
<CustomObject>
    <label>Carro</label>
    <nameField>
        <displayFormat>C{0000}</displayFormat>
        <label>Carro Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/objects/Carro__c/fields/Cor__c.field-meta.xml
<CustomField>
    <fullName>Cor__c</fullName>
    <label>Cor</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/objects/Carro__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/objects/Carro__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/classes/CarrosHnadlerTest.cls
@isTest
public with sharing class CarrosHnadlerTest {


    @isTest static void criaCarroTest(){
        Carro__c carro = new Carro__c();
        carro.Modelo__c = 'civic';
        carro.Nome__c = 'Honda';
        carro.Cor__c = 'Preto';
        CarrosHandler carro = new CarrosHandler();
        carro.criaCarro(carro);
    }

    
    @isTest static void criaCarroTest2(){
        Carro__c carro = new Carro__c();
        carro.Modelo__c = 'Jetta';
        carro.Nome__c = 'Volkswagen';
        carro.Cor__c = 'Preto';
        CarrosHandler carro = new CarrosHandler();
        carro.criaCarro();
    }

}