Treinamento/force-app/main/default/objects/Carro__c/Carro__c.object-meta.xml
<CustomObject>
    <label>Carro</label>
    <nameField>
        <displayFormat>C{0000}</displayFormat>
        <label>Carro Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/objects/Carro__c/fields/Ipva2__c.field-meta.xml
<CustomField>
    <fullName>Ipva2__c</fullName>
    <label>Ipva2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Treinamento/force-app/main/default/objects/Carro__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preco</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Treinamento/force-app/main/default/classes/CarroTriggerHandler.cls
public with sharing class CarroTriggerHandler implements ITriggerHandler
{
    public Boolean IsDisabled()
    {
        return true;
    }
 
    public void BeforeInsert(List<SObject> newItems) {

    }
 
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        Map<Id,Carro__c> carros = (Map<Id,Carro__c>)newItems;
        for(Carro__c qualquer : carros.values()){
            carro.Ipva2__c = carro.Preco__c * 0.04;
        }
    }
 
    public void BeforeDelete(Map<Id, SObject> oldItems) {

    }
 
    public void AfterInsert(Map<Id, SObject> newItems) {
        
    }
 
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}
 
    public void AfterDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterUndelete(Map<Id, SObject> oldItems) {}
}