Treinamento/force-app/main/default/objects/Carro__c/Carro__c.object-meta.xml
<CustomObject>
    <label>Carro</label>
    <nameField>
        <displayFormat>C{0000}</displayFormat>
        <label>Carro Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/objects/Carro__c/fields/Cor__c.field-meta.xml
<CustomField>
    <fullName>Cor__c</fullName>
    <label>Cor</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/objects/Carro__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/objects/Carro__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/objects/Carro__c/fields/Proprietario__c.field-meta.xml
<CustomField>
    <fullName>Proprietario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietario</label>
    <referenceTo>Proprietario__c</referenceTo>
    <relationshipLabel>Carros</relationshipLabel>
    <relationshipName>Carros</relationshipName>
    <type>Lookup</type>
</CustomField>

Treinamento/force-app/main/default/objects/Proprietario__c/Proprietario__c.object-meta.xml
<CustomObject>
    <label>Proprietario</label>
    <nameField>
        <label>Proprietario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/classes/CarrosHandler.cls
public class CarrosHandler {

    //Carro__c carro = new Carro__c();
    //carro.Modelo__c = 'Corolla';
    //carro.Nome__c = 'Toyota';
    //carro.Cor__c = 'Prata';
    
    public Carro__c criaCarro(Carro__c carro){
        salvaCarro(carro);
        Utils util = New Utils();
        util.incrementaNome(carro); 
        return carro;
    }

    public Carro__c criaCarro(Carro__c carro, Proprietario__c prop){
        carro.Proprietario__c = prop.Id;   //criando relacionamento
        salvaCarro(carro);

        return carro;
    }

    private void salvaCarro(Carro__c carro){
        insert carro;
    }



     



}