Treinamento/force-app/main/default/objects/Carro__c/Carro__c.object-meta.xml
<CustomObject>
    <label>Carro</label>
    <nameField>
        <displayFormat>C{0000}</displayFormat>
        <label>Carro Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/objects/Carro__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/classes/BatchbleExemple.cls
global class BatchbleExemple implements Database.Batchable<sObject>{
    public String query;

    global Database.QueryLocator start(Database.BatchableContext BC){ 
        return Database.getQueryLocator(query);  
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Carro__c> carros = (List<Carro__c>)scope;
        for(Carro__c car : carros){
            if(car.Nome__c == 'Volkswagen'){
                car.Nome__c = 'VW';
            }else if(car.Nome__c == 'VW'){
                car.Nome__c = 'Volkswagen';
            }         
        }
        update carros;
    } 

    global void finish(Database.BatchableContext BC){
    }

}