Treinamento/force-app/main/default/objects/Carro__c/Carro__c.object-meta.xml
<CustomObject>
    <label>Carro</label>
    <nameField>
        <displayFormat>C{0000}</displayFormat>
        <label>Carro Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/objects/Carro__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/objects/Carro__c/fields/Proprietario__c.field-meta.xml
<CustomField>
    <fullName>Proprietario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proprietario</label>
    <referenceTo>Proprietario__c</referenceTo>
    <relationshipLabel>Carros</relationshipLabel>
    <relationshipName>Carros</relationshipName>
    <type>Lookup</type>
</CustomField>

Treinamento/force-app/main/default/objects/Proprietario__c/Proprietario__c.object-meta.xml
<CustomObject>
    <label>Proprietario</label>
    <nameField>
        <label>Proprietario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/classes/ProprietarioTriggerHandler.cls
public with sharing class ProprietarioTriggerHandler implements ITriggerHandler
{
    public Boolean IsDisabled()
    {
        return true;
    }
 
    public void BeforeInsert(List<SObject> newItems) {
        
    }
 
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        
    }
 
    public void BeforeDelete(Map<Id, SObject> oldItems) {

    }
 
    public void AfterInsert(Map<Id, SObject> newItems) {
       
    }
 
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        Map<Id,Proprietario__c> proprietarios = (Map<Id,Proprietario__c>)newItems;
        List<Carro__c> carros = [SELECT Nome__c, Proprietario__r.Nome__c FROM Carro__c WHERE Proprietario__c IN :proprietarios.keySet() ];
        for(Carro__c carro : carros){
            carro.Nome__c = carro.Nome__c + ' do ' + carro.Proprietario__r.Nome__c;
        }
        update carros;
    }
 
    public void AfterDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterUndelete(Map<Id, SObject> oldItems) {}
}