Treinamento/force-app/main/default/objects/Proprietario__c/Proprietario__c.object-meta.xml
<CustomObject>
    <label>Proprietario</label>
    <nameField>
        <label>Proprietario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/objects/Proprietario__c/fields/cpf__c.field-meta.xml
<CustomField>
    <fullName>cpf__c</fullName>
    <label>cpf</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/classes/ProprietarioHandler.cls
public with sharing class ProprietarioHandler {
    
    public Proprietario__c criaProprietario(){
        Proprietario__c proprietario = new Proprietario__c();
        proprietario.Name = 'João';
        proprietario.Cpf__c = '88888888888';
        proprietario.Nome__c = ' Silva';
        insert proprietario;
        return proprietario;
    }

    public Proprietario__c criaProprietarioWithCar(){
        Proprietario__c proprietario = new Proprietario__c();
        proprietario.Name = 'José';
        proprietario.Cpf__c = '88888888888';
        proprietario.Nome__c = ' Francisco';
        insert proprietario;
        criaCarroHandler(proprietario);
        return proprietario;
    }

    private void criaCarroHandler(Proprietario__c prop){
        CarrosHandler carHandler = new CarrosHandler();
        carHandler.criaCarro(prop);
    
    }

   

}