Treinamento/force-app/main/default/objects/Proprietario__c/Proprietario__c.object-meta.xml
<CustomObject>
    <label>Proprietario</label>
    <nameField>
        <label>Proprietario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proprietarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Treinamento/force-app/main/default/objects/Proprietario__c/fields/cpf__c.field-meta.xml
<CustomField>
    <fullName>cpf__c</fullName>
    <label>cpf</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Treinamento/force-app/main/default/classes/TreinamentoController.cls
public class TreinamentoController {
    
    public Proprietario__c dono {get;set;}
    public TreinamentoController() {
        dono = [SELECT Id, Nome__c, Cpf__c FROM Proprietario__c
                   WHERE Id = 'a0Of400001E0eKcEAJ'];
    }

    @future
   public Proprietario__c getProprietario(){
       return dono;
   }

   public Pagereference save(){
        update dono;
        PageReference pref = new ApexPages.StandardController(dono).view();
	    return pref;
   }
}